```{r}
library(tidyverse)
diamonds <- read_csv('diamonds.csv')

str(diamonds)
```

1.1

```{r}
library(ggplot2)
ggplot(diamonds, aes(x = carat, y = price)) + geom_point()
ggplot(diamonds, aes(x = carat, y = price, color=clarity)) + geom_point()

```

2.1, 2.2.
```{r}
ggplot(diamonds, aes(x = price)) + geom_histogram(bins = 40) 
ggplot(diamonds, aes(x = price)) + geom_histogram(bins = 40) + scale_x_log10()
```

3.1, 3.2

```{r}
ggplot(diamonds, aes(x = cut, y = price)) + geom_boxplot() + scale_y_log10()
ggplot(diamonds, aes(x = cut, y = price, fill = cut)) + geom_boxplot() + scale_y_log10()
```
4.1,4.2,4.3,4.4

```{r}
filtered_price <- diamonds %>% 
  filter(price > 1000, cut %in% c("Good", "Ideal", "Premium"))

filtered_price
```

```{r}
ggplot(filtered_price, aes(x = cut, y = depth)) + geom_col() + stat = "identity"
```

```{r}
ggplot(filtered_price, aes(x = cut, y = depth)) + geom_col() + facet_wrap(~ clarity)
```

```{r}
ggplot(filtered_price, aes(x = cut, y = depth, fill=clarity)) + geom_col() 
ggplot(filtered_price, aes(x = cut, y = depth, fill=clarity)) + geom_col() + facet_wrap(~ clarity)
```
